### ISSUE TITLE
Package Support - Suggestion

### ISSUE THREAD

**Issue by HypeLevels** [project-error/pe-cli#27]
I think that among with the pre-shown options there should be an input box for the user to input certain packages he would like to be implemented, separated by space or comma, what fits more. One way this would work is standalone, type the packages without selecting any option and it will install those packages, other way it could work is typing the packages AND select an option, that way it would install the option AND the specified packages 😄

**Comment by TasoOneAsia** [comment]
Out of scope. This is basically equivalent to just installing packages yourself with pm of your choice
