### ISSUE TITLE
package.json for react has incorrect homepage 

### ISSUE THREAD

**Issue by Mojito-Fivem** [project-error/pe-cli#36]
# Options to reproduce
```
{
  language: { val: 'TypeScript' },
  resourceName: { val: 'test-react' },
  packages: { val: [] },
  uiFramework: { val: 'react_typescript' }
}
```

# Problem 
The package.json which is being fetched from the [template repository](https://github.com/project-error/cfa-templates/blob/master/react_typescript/package.json) references the homepage as `web/build` but the CLI uses the directory `ui` and not `web`.

# Expected Outcome
homepage matches the folder structure of the generated boilerplate so that the UI can be rendered in-game.

# Actual Outcome
homepage uses the wrong directory

**Comment by itschip** [comment]
Closed it #38
